# 服务端口号
server:
  port: 9002

spring:
  # 配置微服务名称
  application:
    name: gateway-demo
  cloud:
    # 配置cloud nacos
    nacos:
      discovery:
        # nacos服务地址 根据nacos服务所在的机器ip+端口号
        server-addr: 139.159.251.133:8848
        # nacos用户名 可以在nacos服务中创建
        # username: xxxx
        # nacos密码
        # password: xxxx
        # nacos命名空间 需要在nacos服务中命名空间选项中创建 此处不是填写命名空间的名字 而是填写命名空间ID
        namespace: 1f371396-65b8-41d1-ad98-b511bacdd8f8
        # 微服务自定义分组 有写就会根据写的分组 对微服务进行分组 没有则默分配为DEFAULT_GROUP分组
        group: dev_demo
        # 服务权重 数值越大可分配的流量就越多
        weight: 1
    gateway:
      # 开启动态路由功能 有了此配置并可以动态修改配置参数
      discovery:
        locator:
          enabled: true
      routes:
        - id: nacos-demo
          uri: lb://nacos-demo
          # 定义路由匹配的条件，如/item/**的所有路径和/search/**的所有路径
          predicates:
            - Path=/gateway/nacosDemo/**
          filters:
            # 路径重写
            - RewritePath=/gateway/(?<segment>.*), /$\{segment}